# Generated by Django 4.0.4 on 2022-09-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_class',
            field=models.CharField(choices=[('super', 'Superuser'), ('test', 'Test User'), ('cams', 'Cams App Manager'), ('campendium', 'Hypershrub Forest Account'), ('default', 'Default user class')], default='default', max_length=30),
        ),
    ]
