# Generated by Django 4.0.4 on 2022-05-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PkmnSpecies',
            fields=[
                ('natdex', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, null=True, unique=True)),
                ('name_url', models.CharField(max_length=25, null=True, unique=True)),
                ('pronunciation', models.CharField(max_length=25)),
                ('pronounce_anime_URL', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Pokémon species name',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('index', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('id', models.PositiveSmallIntegerField()),
                ('effect', models.TextField()),
                ('power', models.PositiveSmallIntegerField()),
                ('accuracy', models.PositiveSmallIntegerField()),
                ('pp', models.PositiveSmallIntegerField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.type')),
            ],
        ),
        migrations.CreateModel(
            name='LevelupMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.move')),
                ('pkmn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pkmnspecies')),
            ],
            options={
                'verbose_name': 'Level-up Move',
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.TextField()),
                ('when', models.PositiveSmallIntegerField()),
                ('from_pkmn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokedex.pkmnspecies')),
                ('into_pkmn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokedex.pkmnspecies')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesHeader_RBY',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokedex.pkmnspecies')),
                ('hp', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('special', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('catch_rate', models.PositiveSmallIntegerField()),
                ('base_exp', models.PositiveSmallIntegerField()),
                ('tmhm_bits', models.BinaryField()),
                ('growth_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.growthrate')),
                ('type1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_one', to='pokedex.type')),
                ('type2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_two', to='pokedex.type')),
            ],
            options={
                'verbose_name': 'Pokémon species data, RBY',
                'verbose_name_plural': 'Pokémon species data, RBY',
            },
        ),
    ]
