# Generated by Django 4.0.4 on 2022-05-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_long', models.CharField(blank=True, max_length=100)),
                ('gen', models.PositiveSmallIntegerField(blank=True)),
                ('series', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('effect', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PkmnSpecies',
            fields=[
                ('natdex', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, null=True, unique=True)),
                ('name_url', models.CharField(max_length=25, null=True, unique=True)),
                ('pronunciation', models.CharField(blank=True, max_length=25)),
                ('pronounce_anime_URL', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Pokémon species',
                'verbose_name_plural': 'Pokémon species',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name_url', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pkmn_RBY',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('hp', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('special', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('catch_rate', models.PositiveSmallIntegerField()),
                ('base_exp', models.PositiveSmallIntegerField()),
                ('growth_rate', models.CharField(max_length=20)),
                ('tmhm_bits', models.BinaryField()),
                ('pkmn', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pkmnspecies')),
                ('type1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_one', to='pokedex.type')),
                ('type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_two', to='pokedex.type')),
            ],
            options={
                'verbose_name': 'Pokémon species data, RBY',
                'verbose_name_plural': 'Pokémon species data, RBY',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name_url', models.CharField(blank=True, max_length=25)),
                ('id', models.PositiveSmallIntegerField(blank=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('power', models.PositiveSmallIntegerField(blank=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True)),
                ('pp', models.PositiveSmallIntegerField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.type')),
            ],
        ),
        migrations.CreateModel(
            name='LevelupMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.move')),
                ('pkmn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pkmnspecies')),
            ],
            options={
                'verbose_name': 'Level-up Move',
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('how', models.CharField(blank=True, max_length=200)),
                ('when', models.PositiveSmallIntegerField(blank=True)),
                ('into', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkmn_into', to='pokedex.pkmnspecies')),
                ('pkmn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkmn_from', to='pokedex.pkmnspecies')),
            ],
        ),
    ]
