# Generated by Django 4.0.4 on 2022-05-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmn_rby',
            name='pkmn',
            field=models.ForeignKey(db_column='pkmn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pkmnspecies', to_field='name'),
        ),
    ]
