# Generated by Django 4.0.4 on 2022-05-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='levelupmove',
            name='game',
            field=models.ForeignKey(blank=True, db_column='game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.game', to_field='abbreviation'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='into',
            field=models.ForeignKey(db_column='into', on_delete=django.db.models.deletion.CASCADE, related_name='pkmn_into', to='pokedex.pkmnspecies', to_field='name'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='pkmn',
            field=models.ForeignKey(db_column='pkmn', on_delete=django.db.models.deletion.CASCADE, related_name='pkmn_from', to='pokedex.pkmnspecies', to_field='name'),
        ),
        migrations.AlterField(
            model_name='levelupmove',
            name='pkmn',
            field=models.ForeignKey(db_column='pkmn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pkmnspecies', to_field='name'),
        ),
    ]
