# Generated by Django 4.0.4 on 2022-05-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_long', models.CharField(max_length=100, unique=True)),
                ('series', models.CharField(max_length=10)),
            ],
        ),
    ]
