# Generated by Django 4.0.4 on 2022-09-10 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CamsApp',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('codename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CamsModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fields', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camsapp')),
            ],
        ),
        migrations.CreateModel(
            name='CamsModelInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('filepath', models.TextField(blank=True)),
                ('cams_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CamsFileTree',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('codename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camsapp')),
            ],
        ),
        migrations.CreateModel(
            name='CamsAppAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='cams.camsapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CamsActionLocal',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('codename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('cams_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CamsActionGlobal',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('codename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camsapp')),
            ],
        ),
    ]
