# Generated by Django 4.0.7 on 2022-09-21 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0003_camsformresponse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camsmodelinstance',
            name='id',
            field=models.TextField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
